# Generated by Django 4.0.1 on 2022-01-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=130)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
